### ISSUE TITLE
 local variable 'audiosr' referenced before assignment

### ISSUE THREAD

**Issue by hanctRaise** [sh-lee-prml/HierSpeechpp#9]
When i run sh inference.sh, i met this error

`
Initializing Inference Process..
/home/hanct/anaconda3/envs/hier/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/hanct/snap/snapd-desktop-integration/83/Documents/HierSpeechpp/inference.py", line 224, in <module>
    main()
  File "/home/hanct/snap/snapd-desktop-integration/83/Documents/HierSpeechpp/inference.py", line 221, in main
    inference(a)
  File "/home/hanct/snap/snapd-desktop-integration/83/Documents/HierSpeechpp/inference.py", line 183, in inference
    hierspeech = model_load(a) 
  File "/home/hanct/snap/snapd-desktop-integration/83/Documents/HierSpeechpp/inference.py", line 162, in model_load
    utils.load_checkpoint(a.ckpt_sr48, audiosr, None)
UnboundLocalError: local variable 'audiosr' referenced before assignment
`
Look like something missing. What is this audiosr variable?

**Comment by sh-lee-prml** [comment]
Sorry. I fixed it now. During changing some variables, I made a mistake.
